export const GeneralBloodTestQueryKeys = {
  GENERAL_BLOOD_TESTS: "GENERAL_BLOOD_TESTS",
  LAST_GENERAL_BLOOD_TEST: "LAST_GENERAL_BLOOD_TEST",
  GENERAL_BLOOD_TESTS_SELECT: "GENERAL_BLOOD_TESTS_SELECT",
};
