export const UserQueryKeys = {
  USERS: "USERS",
  USERS_SELECT: "USERS_SELECT",

  FARMERS: "FARMERS",
  FARMERS_SELECT: "FARMERS_SELECT",

  VETERINARIANS: "VETERINARIANS",
  VETERINARIANS_SELECT: "VETERINARIANS_SELECT",
};
