export const GeneralInspectionQueryKeys = {
  GENERAL_INSPECTION: "GENERAL_INSPECTION",
  LAST_GENERAL_INSPECTION: "LAST_GENERAL_INSPECTION",
  GENERAL_INSPECTION_SELECT: "GENERAL_INSPECTION_SELECT",
};
